- name: Log in to Concourse
  ansible.builtin.shell: |
    fly -t {{ concourse_target }} login \
      -c {{ concourse_url }} \
      -u {{ concourse_user }} \
      -p {{ concourse_password }}
  delegate_to: localhost
